### ISSUE TITLE
Download PDF with the dark mode

### ISSUE THREAD

**Issue by vicnetto** [ArshSB/DarkPDF#3]
Hey @ArshSB, congrats for the amazing extension, I'm enjoying a lot! 

I would like to know if there is any way to download the PDF with the Dark Mode? I tried a lot of things, but none of them worked. 

Thanks in advance for your answer!

**Comment by ArshSB** [comment]
Hi Victor,

I am glad you found this extension useful! Unfortunately, the feature you are asking is out of the scope of this extension. The way the dark mode works is that I add a layer over the PDF that inverts the colors. So the actual PDF remains unchanged, which is why you can't download it with dark mode.

I think that a way to accomplish what you want is by changing the PDF background and text properties, through software like Adobe Acrobat or equivalent.

Thank you for the question. Take care!
