### ISSUE TITLE
Dark Mode turns off with tab change

### ISSUE THREAD

**Issue by Reidemption** [ArshSB/DarkPDF#7]
I've been using the extension for about an hour now and I noticed that when I switch between multiple tabs in Chrome the "automatically turn dark mode on" doesn't seem to be working as intended i.e. I have a white background when I switch back. I'm more than willing to try and help out with this project and try to figure out how to help if you could point me in some direction as I've never worked with chrome extensions before.

**Comment by ArshSB** [comment]
Hello there,

I appreciate your interest in working on this bug. I actually have known about this issue for some time but just never had the time to look into a solution. I'll try to give you some basic information about it so you can start with your own investigation.

Right now `background.js` saves all of the tabs opened by the user in a list, so that when the user switches between them, `toggle.js` is not run multiple times on the same tab. `background.js` is a service worker as specified in `manifest.json`, and since [service workers are terminated when not in use and restarted when needed](https://developer.chrome.com/docs/extensions/mv3/migrating_to_service_workers/#state:~:text=service%20workers%20are%20terminated%20when%20not%20in%20use%20and%20restarted%20when%20needed), our list of tabs is lost. 

The solution for this would be using the Storage API to add a state for the list of tabs so that we have access to it even after `background.js` is terminated. You can start by reading [this](https://developer.chrome.com/docs/extensions/mv3/migrating_to_service_workers/#state), adding the appropriate code to `background.js` and testing it locally via `Load unpacked` option on `chrome://extensions`. After your done, feel free to open a pull request and I'll take a look.

Hope this helps and best of luck!
